In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/student_performance.csv")
df.head()# Printing first 5 rows of dataset

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final
0,1,Ali,M,16,5,90,9,75,72,80
1,2,Ahmed,M,15,3,70,6,55,60,58
2,3,Sara,F,16,7,95,10,88,85,92
3,4,Fatima,F,15,6,92,9,82,80,87
4,5,Usman,M,16,2,65,5,48,52,50

In [4]:
#Adding new features like columns Average_Score and Improvement
# Average score of mid term and final
df["Average_Score"] = (
    df["Midterm"] + df["Final"]
) / 2
df.head()

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score
0,1,Ali,M,16,5,90,9,75,72,80,77.5
1,2,Ahmed,M,15,3,70,6,55,60,58,56.5
2,3,Sara,F,16,7,95,10,88,85,92,90.0
3,4,Fatima,F,15,6,92,9,82,80,87,84.5
4,5,Usman,M,16,2,65,5,48,52,50,49.0

In [5]:
df["Improvement"] = df["Final"] - df["Previous_Score"]
df.head()

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score,Improvement
0,1,Ali,M,16,5,90,9,75,72,80,77.5,8
1,2,Ahmed,M,15,3,70,6,55,60,58,56.5,-2
2,3,Sara,F,16,7,95,10,88,85,92,90.0,7
3,4,Fatima,F,15,6,92,9,82,80,87,84.5,7
4,5,Usman,M,16,2,65,5,48,52,50,49.0,-2

In [6]:
def grade_category(score):
    if score >= 90:
        return "Excellent"
    elif score >= 80:
        return "Very Good"
    elif score >= 70:
        return "Good"
    elif score >= 60:
        return "Average"
    elif score >= 50:
        return "Needs Improvement"
    else:
        return "At Risk"

In [7]:
df["Category"] = df["Final"].apply(
    grade_category
)

In [8]:
df[["Name", "Final", "Category"]]

       Name  Final           Category
0       Ali     80          Very Good
1     Ahmed     58  Needs Improvement
2      Sara     92          Excellent
3    Fatima     87          Very Good
4     Usman     50  Needs Improvement
5    Ayesha     95          Excellent
6     Bilal     72               Good
7      Zain     65            Average
8    Maryam     98          Excellent
9    Hassan     42            At Risk
10     Hina     82          Very Good
11    Hamza     76               Good
12     Noor     89          Very Good
13  Daniyal     52  Needs Improvement
14     Eman     94          Excellent

In [9]:
print(f"Average final score:{df["Final"].mean():.2f}")

Average final score:75.47

In [10]:
# Who scored highest marks
print(f"The student who scored highest marks:{df.loc[df['Final'].idxmax()]}")

The student who scored highest marks:Student_ID                9
Name                 Maryam
Gender                    F
Age                      16
Study_Hours               9
Attendance               99
Assignments              10
Midterm                  95
Previous_Score           94
Final                    98
Average_Score          96.5
Improvement               4
Category          Excellent
Name: 8, dtype: object

In [11]:
# Who scored lowest marks
print(f"The student who scored lowest marks:{df.loc[df['Final'].idxmin()]}")

The student who scored lowest marks:Student_ID             10
Name               Hassan
Gender                  M
Age                    15
Study_Hours             1
Attendance             55
Assignments             4
Midterm                40
Previous_Score         45
Final                  42
Average_Score        41.0
Improvement            -3
Category          At Risk
Name: 9, dtype: object

In [12]:
# The students with attendance more than 90%
df[df["Attendance"] > 90]

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score,Improvement,Category
2,3,Sara,F,16,7,95,10,88,85,92,90.0,7,Excellent
3,4,Fatima,F,15,6,92,9,82,80,87,84.5,7,Very Good
5,6,Ayesha,F,15,8,98,10,92,90,95,93.5,5,Excellent
8,9,Maryam,F,16,9,99,10,95,94,98,96.5,4,Excellent
12,13,Noor,F,16,7,93,9,86,84,89,87.5,5,Very Good
14,15,Eman,F,16,8,97,10,90,91,94,92.0,3,Excellent

In [13]:
# Students studying more than 6 hours
df[df["Study_Hours"] > 6]

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score,Improvement,Category
2,3,Sara,F,16,7,95,10,88,85,92,90.0,7,Excellent
5,6,Ayesha,F,15,8,98,10,92,90,95,93.5,5,Excellent
8,9,Maryam,F,16,9,99,10,95,94,98,96.5,4,Excellent
12,13,Noor,F,16,7,93,9,86,84,89,87.5,5,Very Good
14,15,Eman,F,16,8,97,10,90,91,94,92.0,3,Excellent

In [14]:
# Students scoring above 80
df[df["Final"] > 80]

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score,Improvement,Category
2,3,Sara,F,16,7,95,10,88,85,92,90.0,7,Excellent
3,4,Fatima,F,15,6,92,9,82,80,87,84.5,7,Very Good
5,6,Ayesha,F,15,8,98,10,92,90,95,93.5,5,Excellent
8,9,Maryam,F,16,9,99,10,95,94,98,96.5,4,Excellent
10,11,Hina,F,16,6,88,8,78,75,82,80.0,7,Very Good
12,13,Noor,F,16,7,93,9,86,84,89,87.5,5,Very Good
14,15,Eman,F,16,8,97,10,90,91,94,92.0,3,Excellent

In [15]:
# Top students
df.sort_values(
    by="Final",
    ascending=False
)

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score,Improvement,Category
8,9,Maryam,F,16,9,99,10,95,94,98,96.5,4,Excellent
5,6,Ayesha,F,15,8,98,10,92,90,95,93.5,5,Excellent
14,15,Eman,F,16,8,97,10,90,91,94,92.0,3,Excellent
2,3,Sara,F,16,7,95,10,88,85,92,90.0,7,Excellent
12,13,Noor,F,16,7,93,9,86,84,89,87.5,5,Very Good
3,4,Fatima,F,15,6,92,9,82,80,87,84.5,7,Very Good
10,11,Hina,F,16,6,88,8,78,75,82,80.0,7,Very Good
0,1,Ali,M,16,5,90,9,75,72,80,77.5,8,Very Good
11,12,Hamza,M,15,5,85,8,72,70,76,74.0,6,Good
6,7,Bilal,M,16,4,80,7,65,68,72,68.5,4,Good
7,8,Zain,M,15,3,75,6,58,62,65,61.5,3,Average
1,2,Ahmed,M,15,3,70,6,55,60,58,56.5,-2,Needs Improvement
13,14,Daniyal,M,15,2,60,5,50,48,52,51.0,4,Needs Improvement
4,5,Usman,M,16,2,65,5,48,52,50,49.0,-2,Needs Improvement
9,10,Hassan,M,15,1,55,4,40,45,42,41.0,-3,At Risk

In [16]:
# Bottom Students
df.sort_values(
    by="Final"
)

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score,Improvement,Category
9,10,Hassan,M,15,1,55,4,40,45,42,41.0,-3,At Risk
4,5,Usman,M,16,2,65,5,48,52,50,49.0,-2,Needs Improvement
13,14,Daniyal,M,15,2,60,5,50,48,52,51.0,4,Needs Improvement
1,2,Ahmed,M,15,3,70,6,55,60,58,56.5,-2,Needs Improvement
7,8,Zain,M,15,3,75,6,58,62,65,61.5,3,Average
6,7,Bilal,M,16,4,80,7,65,68,72,68.5,4,Good
11,12,Hamza,M,15,5,85,8,72,70,76,74.0,6,Good
0,1,Ali,M,16,5,90,9,75,72,80,77.5,8,Very Good
10,11,Hina,F,16,6,88,8,78,75,82,80.0,7,Very Good
3,4,Fatima,F,15,6,92,9,82,80,87,84.5,7,Very Good
12,13,Noor,F,16,7,93,9,86,84,89,87.5,5,Very Good
2,3,Sara,F,16,7,95,10,88,85,92,90.0,7,Excellent
14,15,Eman,F,16,8,97,10,90,91,94,92.0,3,Excellent
5,6,Ayesha,F,15,8,98,10,92,90,95,93.5,5,Excellent
8,9,Maryam,F,16,9,99,10,95,94,98,96.5,4,Excellent

In [22]:
# Group Analysis 
# Average marks by gender
df.groupby("Gender")["Final"].mean().map('{:.2f}%'.format)

Gender
F    91.00%
M    61.88%
Name: Final, dtype: object

In [23]:
# Group Analysis 
# Average attendance by gender
df.groupby("Gender")["Attendance"].mean().map('{:.2f}%'.format)

Gender
F    94.57%
M    72.50%
Name: Attendance, dtype: object

In [24]:
# Count students by category
df["Category"].value_counts()

Category
Very Good            4
Excellent            4
Needs Improvement    3
Good                 2
Average              1
At Risk              1
Name: count, dtype: int64

In [26]:
#Correlation Analysis
#Relationship between numerical columns:
df.select_dtypes(
   include="number" 
).corr()

,Student_ID,Age,Study_Hours,Attendance,Assignments,Midterm,Previous_Score,Final,Average_Score,Improvement
Student_ID,1.000000e+00,2.472381e-16,0.089734,-0.051640,-0.061247,0.036666,0.021144,0.016684,0.026609,-0.009142
Age,2.472381e-16,1.000000e+00,0.414462,0.424383,0.406650,0.404280,0.410987,0.405075,0.405062,0.242792
Study_Hours,8.973376e-02,4.144625e-01,1.000000,0.964639,0.965448,0.990908,0.990710,0.981065,0.986870,0.609239
Attendance,-5.164049e-02,4.243830e-01,0.964639,1.000000,0.987337,0.984896,0.979510,0.992087,0.989455,0.717462
Assignments,-6.124681e-02,4.066499e-01,0.965448,0.987337,1.000000,0.986129,0.973268,0.986101,0.987043,0.714637
Midterm,3.666612e-02,4.042800e-01,0.990908,0.984896,0.986129,1.000000,0.989421,0.996238,0.999042,0.694074
Previous_Score,2.114404e-02,4.109865e-01,0.990710,0.979510,0.973268,0.989421,1.000000,0.988216,0.989744,0.604290
Final,1.668410e-02,4.050749e-01,0.981065,0.992087,0.986101,0.996238,0.988216,1.000000,0.999076,0.719125
Average_Score,2.660891e-02,4.050622e-01,0.986870,0.989455,0.987043,0.999042,0.989744,0.999076,1.000000,0.707379
Improvement,-9.141924e-03,2.427922e-01,0.609239,0.717462,0.714637,0.694074,0.604290,0.719125,0.707379,1.000000